<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.verification</groupId>
    <artifactId>standalone-verifier</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <alloyinecore.lib.dir>../../alloy-in-ecore-java-verification/AlloyInEcore/Source/eu.modelwriter.core.alloyinecore/lib</alloyinecore.lib.dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.modelwriter.core</groupId>
            <artifactId>alloyinecore</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>kodkod</groupId>
            <artifactId>kodkod</artifactId>
            <version>2.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/kodkod.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.microsoft.z3</groupId>
            <artifactId>com.microsoft.z3</artifactId>
            <version>4.6.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/com.microsoft.z3.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore</artifactId>
            <version>2.12.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.ecore_2.12.0.v20160420-0247.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.common</artifactId>
            <version>2.12.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.common_2.12.0.v20160420-0247.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore.xmi</artifactId>
            <version>2.12.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.compare</artifactId>
            <version>3.5.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.compare_3.5.0.201706130827.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-runtime</artifactId>
            <version>4.7</version>
        </dependency>
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>ST4</artifactId>
            <version>4.0.8</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>
        <dependency>
            <groupId>org.sat4j</groupId>
            <artifactId>org.sat4j.core</artifactId>
            <version>2.3.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/${alloyinecore.lib.dir}/org.sat4j.core-2.3.1.jar</systemPath>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <mainClass>com.verification.Main</mainClass>
                    <systemProperties>
                        <systemProperty>
                            <key>java.library.path</key>
                            <value>${project.basedir}/${alloyinecore.lib.dir}/SatSolvers</value>
                        </systemProperty>
                    </systemProperties>
                    <additionalClasspathElements>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/kodkod.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/com.microsoft.z3.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.ecore_2.12.0.v20160420-0247.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.common_2.12.0.v20160420-0247.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/org.eclipse.emf.compare_3.5.0.201706130827.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/org.sat4j.core-2.3.1.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/antlr4-runtime-4.6.jar</additionalClasspathElement>
                        <additionalClasspathElement>${project.basedir}/${alloyinecore.lib.dir}/antlr4-4.6.jar</additionalClasspathElement>
                    </additionalClasspathElements>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
